development:
  access_key: MY-DEV-ACCESS-KEY
  secret_key: MY-DEV-SECRET-KEY
  region: eu-west-1
  application_name: development_larva_spawn
  queue_suffix:

production:
  access_key: MY-PRODUCTION-ACCESS-KEY
  secret_key: MY-PRODUCTION-SECRET-KEY
  region: eu-west-1
  application_name: larva_spawn
  queue_suffix:
